### ISSUE TITLE
Passthrough routes don't work

### ISSUE THREAD

**Issue by parag-datar** [rwjblue/pretender-query-param-handler#3]
I was expecting that QueryParamAwarePretender should allow me to passthrough requests to certain routes similar to Pretender. I tried doing the following but that didn't work:
```
const server = new QueryParamAwarePretender(function() {
  this.get('/photos/:id', this.passthrough);
});
```
It fails since `pathnameHandlersMap` is not defined on the instance yet.
Am I missing something?

**Comment by hjdivad** [comment]
Fixed in [v1.3.0](https://github.com/rwjblue/pretender-query-param-handler/blob/main/CHANGELOG.md#v130-2022-01-21)
